version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: rtt_postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-rtt_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/00_init.sql:/docker-entrypoint-initdb.d/00_init.sql

volumes:
  postgres_data:
